language: julia
julia:
  - 1.5

script:
  - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl

before_deploy:
  - julia --project=./ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=./ test/runtests.jl

deploy:
- provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: "./docs/build/"
  skip-cleanup: true
  on:
    branch: master