language: julia
julia:
  - 1.6

script:
  - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl
  - julia --project=./ -e 'using Pkg; Pkg.instantiate()'
  - julia --project=./ --code-coverage test/runtests.jl

deploy:
- provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: "./docs/build/"
  skip-cleanup: true
  on:
    branch: master

after_success:
  - julia --project=./ -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'