language: julia
julia:
  - 1.6

services:
  - docker

deploy:
- provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: "./docs/build/"
  skip-cleanup: true
  on:
    branch: master

jobs:
  include:
    - stage: build docker image
      script: bash ./build.sh