version: "2"

services:
  pdag_extensions:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - H_UID=1000
        - H_GID=1000
    container_name: pdag_extensions
    tty: true
    volumes:
      - ./benchmarks/:/home/user/benchmarks/
      - ./configs/:/home/user/configs/
      - ./docs/:/home/user/docs/
      - ./logs/:/home/user/logs/
      - ./src/:/home/user/src/
      - ./test/:/home/user/test/
      - ./Manifest.toml:/home/user/Manifest.toml
      - ./Project.toml:/home/user/Project.toml
    entrypoint: /bin/bash