version: "2"

services:
  pdag_extensions:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - H_UID=1000
        - H_GID=1000
    container_name: pdag_extensions
    tty: true
    volumes:
      - ./configs/:/home/user/configs/
      - ./src/:/home/user/src/
    entrypoint: /bin/bash